// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type BerryReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *BerryReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type BerryReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	BerryReadDefaultTextPlainString *string
}

func (o *BerryReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *BerryReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *BerryReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *BerryReadResponse) GetBerryReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.BerryReadDefaultTextPlainString
}
