// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type BerryFlavorReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *BerryFlavorReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type BerryFlavorReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	BerryFlavorReadDefaultTextPlainString *string
}

func (o *BerryFlavorReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *BerryFlavorReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *BerryFlavorReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *BerryFlavorReadResponse) GetBerryFlavorReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.BerryFlavorReadDefaultTextPlainString
}
