// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type EncounterConditionListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *EncounterConditionListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *EncounterConditionListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type EncounterConditionListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	EncounterConditionListDefaultTextPlainString *string
}

func (o *EncounterConditionListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EncounterConditionListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EncounterConditionListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *EncounterConditionListResponse) GetEncounterConditionListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.EncounterConditionListDefaultTextPlainString
}
