// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type EncounterMethodReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *EncounterMethodReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type EncounterMethodReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	EncounterMethodReadDefaultTextPlainString *string
}

func (o *EncounterMethodReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EncounterMethodReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EncounterMethodReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *EncounterMethodReadResponse) GetEncounterMethodReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.EncounterMethodReadDefaultTextPlainString
}
