// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type EvolutionTriggerReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *EvolutionTriggerReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type EvolutionTriggerReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	EvolutionTriggerReadDefaultTextPlainString *string
}

func (o *EvolutionTriggerReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EvolutionTriggerReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EvolutionTriggerReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *EvolutionTriggerReadResponse) GetEvolutionTriggerReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.EvolutionTriggerReadDefaultTextPlainString
}
