// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GenderReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GenderReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type GenderReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	GenderReadDefaultTextPlainString *string
}

func (o *GenderReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenderReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenderReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GenderReadResponse) GetGenderReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.GenderReadDefaultTextPlainString
}
