// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GenderListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *GenderListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GenderListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type GenderListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	GenderListDefaultTextPlainString *string
}

func (o *GenderListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenderListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenderListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GenderListResponse) GetGenderListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.GenderListDefaultTextPlainString
}
