// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GenerationReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GenerationReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type GenerationReadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Default response
	GenerationReadDefaultTextPlainString *string
}

func (o *GenerationReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenerationReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenerationReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GenerationReadResponse) GetGenerationReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.GenerationReadDefaultTextPlainString
}
