// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ItemAttributeReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *ItemAttributeReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type ItemAttributeReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	ItemAttributeReadDefaultTextPlainString *string
}

func (o *ItemAttributeReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ItemAttributeReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ItemAttributeReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ItemAttributeReadResponse) GetItemAttributeReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.ItemAttributeReadDefaultTextPlainString
}
