// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ItemPocketReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *ItemPocketReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type ItemPocketReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	ItemPocketReadDefaultTextPlainString *string
}

func (o *ItemPocketReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ItemPocketReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ItemPocketReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ItemPocketReadResponse) GetItemPocketReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.ItemPocketReadDefaultTextPlainString
}
