// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type LanguageListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *LanguageListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *LanguageListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type LanguageListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	LanguageListDefaultTextPlainString *string
}

func (o *LanguageListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LanguageListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LanguageListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *LanguageListResponse) GetLanguageListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.LanguageListDefaultTextPlainString
}
