// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type LocationListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *LocationListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *LocationListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type LocationListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	LocationListDefaultTextPlainString *string
}

func (o *LocationListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LocationListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LocationListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *LocationListResponse) GetLocationListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.LocationListDefaultTextPlainString
}
