// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type MoveAilmentReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *MoveAilmentReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type MoveAilmentReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	MoveAilmentReadDefaultTextPlainString *string
}

func (o *MoveAilmentReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MoveAilmentReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MoveAilmentReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MoveAilmentReadResponse) GetMoveAilmentReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.MoveAilmentReadDefaultTextPlainString
}
