// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type MoveLearnMethodListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *MoveLearnMethodListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *MoveLearnMethodListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type MoveLearnMethodListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	MoveLearnMethodListDefaultTextPlainString *string
}

func (o *MoveLearnMethodListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MoveLearnMethodListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MoveLearnMethodListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MoveLearnMethodListResponse) GetMoveLearnMethodListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.MoveLearnMethodListDefaultTextPlainString
}
