// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type MoveDamageClassReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *MoveDamageClassReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type MoveDamageClassReadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Default response
	MoveDamageClassReadDefaultTextPlainString *string
}

func (o *MoveDamageClassReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MoveDamageClassReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MoveDamageClassReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MoveDamageClassReadResponse) GetMoveDamageClassReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.MoveDamageClassReadDefaultTextPlainString
}
