// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type MoveTargetReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *MoveTargetReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type MoveTargetReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	MoveTargetReadDefaultTextPlainString *string
}

func (o *MoveTargetReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MoveTargetReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MoveTargetReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MoveTargetReadResponse) GetMoveTargetReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.MoveTargetReadDefaultTextPlainString
}
