// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type NatureListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *NatureListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *NatureListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type NatureListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	NatureListDefaultTextPlainString *string
}

func (o *NatureListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *NatureListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *NatureListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *NatureListResponse) GetNatureListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.NatureListDefaultTextPlainString
}
