// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PalParkAreaListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *PalParkAreaListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PalParkAreaListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type PalParkAreaListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Default response
	PalParkAreaListDefaultTextPlainString *string
}

func (o *PalParkAreaListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PalParkAreaListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PalParkAreaListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PalParkAreaListResponse) GetPalParkAreaListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.PalParkAreaListDefaultTextPlainString
}
