// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PalParkAreaReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PalParkAreaReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type PalParkAreaReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	PalParkAreaReadDefaultTextPlainString *string
}

func (o *PalParkAreaReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PalParkAreaReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PalParkAreaReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PalParkAreaReadResponse) GetPalParkAreaReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.PalParkAreaReadDefaultTextPlainString
}
