// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PokemonListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *PokemonListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PokemonListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type PokemonListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	PokemonListDefaultTextPlainString *string
}

func (o *PokemonListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PokemonListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PokemonListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PokemonListResponse) GetPokemonListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.PokemonListDefaultTextPlainString
}
