// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PokemonFormReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PokemonFormReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type PokemonFormReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	PokemonFormReadDefaultTextPlainString *string
}

func (o *PokemonFormReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PokemonFormReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PokemonFormReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PokemonFormReadResponse) GetPokemonFormReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.PokemonFormReadDefaultTextPlainString
}
