// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type StatListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *StatListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *StatListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type StatListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	StatListDefaultTextPlainString *string
}

func (o *StatListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *StatListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *StatListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *StatListResponse) GetStatListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.StatListDefaultTextPlainString
}
