// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type SuperContestEffectReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *SuperContestEffectReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type SuperContestEffectReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	SuperContestEffectReadDefaultTextPlainString *string
}

func (o *SuperContestEffectReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SuperContestEffectReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SuperContestEffectReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *SuperContestEffectReadResponse) GetSuperContestEffectReadDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.SuperContestEffectReadDefaultTextPlainString
}
