// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type TypeListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *TypeListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *TypeListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type TypeListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	TypeListDefaultTextPlainString *string
}

func (o *TypeListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TypeListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TypeListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TypeListResponse) GetTypeListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.TypeListDefaultTextPlainString
}
