// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type VersionListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *VersionListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *VersionListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type VersionListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default response
	VersionListDefaultTextPlainString *string
}

func (o *VersionListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *VersionListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *VersionListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *VersionListResponse) GetVersionListDefaultTextPlainString() *string {
	if o == nil {
		return nil
	}
	return o.VersionListDefaultTextPlainString
}
